jobs:
  - name: main
    command: ./main.py update-db
    schedule:
      minute: "*/3"
      hour: "0"
    failsWhen:
      producesStdout: false
      producesStderr: false
      nonzeroReturn: true
    concurrencyPolicy: Forbid
    user: root
